artifact_location: /Users/kumarrohit/Desktop/Aerial-Object-Detection/Aerial-Object-Detection/YOLOv8Dataset/runs/mlflow/764526516035700500
creation_time: 1729661589488
experiment_id: '764526516035700500'
last_update_time: 1729661589488
lifecycle_stage: active
name: /Shared/YOLOv8
