artifact_location: /Users/kumarrohit/Desktop/Aerial-Object-Detection/Aerial-Object-Detection/YOLOv8Dataset/runs/mlflow/0
creation_time: 1729661589476
experiment_id: '0'
last_update_time: 1729661589476
lifecycle_stage: active
name: Default
